//: Deep into compiling
Platform; /// here is everything you need
Platform.userAppSupportDir; // all customizations for your user
Platform.userExtensionDir; // put here your own Classes and modifications
Platform.dumpFullInterface;
Platform.systemAppSupportDir;
Platform.systemExtensionDir;
Platform.userConfigDir;
Platform.resourceDir;
Platform.recordingsDir;
Platform.defaultTempDir;
Platform.platformDir;
