// Use symbols to store and access all basic types of user objects
// Send messages to symbols to access and interact with basic type of objects:
\something.p       // a player: play synth or pattern
\something.e       // an Environment storing control parameters for a player
\something.b       // a buffer
\something.bus     // a bus
\something.window  // a window
\something.v       // a window with vertically stacked widgets
\something.osc;    // an OSC control object
//:edited