13 Aug 2020 09:14

Methods for syncing various kinds of objects.

N.B. 1: server always defaults to Server.default.
N.B. 2: Buffer 

- aFunction.sync(optional: server) :: Add the function to Que for synced allocation.
- aSynthDef.sync(opitonal: server) :: Add a function that adds the synthdef to the server for synced allocation.
- aString.sync(optional: server) :: Add a function that loads the file given by path aString.
- Buffer.allocSync :: Like Buffer.alloc, but execution is synced by Que.  Returns the new buffer.  The buffer instance is created immediately on sclang and returned, but the message for allocating the buffer on the server is sent later in the order given by the Que sync.
- Buffer.readSync :: Like Buffer.read, but execution is synced by Que.  Returns the new buffer.  The buffer instance is created immediately on sclang and returned, but the message for reading the buffer on the server is sent later in the order given by the Que sync.

* Alternatives

- anArray.sync(optional: server) :: Add function that allocs buffer specified by anArray.  Format is: [numChannels = 1, numFrames = 44100]
- aString.readSync(optional: server, numFrames) :: 
