// 16 Sep 2017 20:36
// Test for ordering targets using OrderedGroup;

OrderedGroup.last;
OrderedGroup.all;
OrderedGroup before: OrderedGroup.last;
OrderedGroup before: ( OrderedGroup before: (OrderedGroup before: OrderedGroup.last;));
//:
Server.default.defaultGroup.asTarget.server;

\default +> \test;

currentEnvironment;

\test.ev;
// ================================================================
//: Testing recent additions to lib for ordering of groups
\test.ev canAddWriter: \test.ev;
//:
\test.ev canAddWriter: \writer1.ev;
//:
\test.ev addWriter: \test.ev;
//:
\test.ev addWriter: \writer1.ev;
//:
\test.ev;
//:
\writer1.ev;
//:
