// 16 Sep 2017 20:36
// Test for ordering targets using OrderedGroup;

OrderedGroup.last;
OrderedGroup.all;
OrderedGroup before: OrderedGroup.last;
OrderedGroup before: ( OrderedGroup before: (OrderedGroup before: OrderedGroup.last;));
//:
Server.default.defaultGroup.asTarget.server;

\default +> \test;

currentEnvironment;

\test.e;
// ================================================================
//: Testing recent additions to lib for ordering of groups
\test.e canAddWriter: \test.e;
//:
\test.e canAddWriter: \writer1.e;
//:
\test.e addWriter: \test.e;
//:
\test.e addWriter: \writer1.e;
//:
\test.e;
//:
\writer1.e;
//:
